In [ ]:
### Quick Recap

# "Objects" are a programming structure that joins functions and data together
# That is, "objects" are structures with "methods" (i.e., functions) and "attributes" (i.e., data)
# You can access or use an object's methods or functions using: <object>.<attributes/methods>
# Lists are one example of an object and they have a .sort() method that sorts the elements of the list
l = [1,6,2]
l.sort() # here we are using the sort method of the list object "l"
# Most things in Python are objects

# Importing libraries
# basic way of importing a library
import numpy 
# import a library under an alias
import numpy as np
# import just a specific set of functions from a library
from numpy import array, unique, arange



In [ ]:
### Numpy
# numpy is probably the most useful and widely used Python library for neuroimaging
# It gives you access to lots of numerical functions (e.g., interpolation, filtering, random numbers)
# and implements a very useful data structure called an "array"
# There is also an "array" object that is native to Python, but it's not used much in neuroimaging because
# numpy is ubiquitous and offers more features.

In [10]:
### Arrays
# an array is basically a matrix with arbitrarily many dimensions
# (or more accurately a "tensor", because strictly speaking matrices are 2D)
import numpy as np
#an easy way to create an array is to write a list and convert it to an array
myArray = np.array( [ [1,2,3], [4,5,6]] )

#arrays can be indexed, much like lists
print(myArray[0])
print(myArray[1])
print(myArray[0][0])
print(myArray[1][2])



# Unlike lists, arrays must have: 
#    1. Elements that are all of the same data type
myList0 = [ 0, 1]
print( np.array(myList0))
myList1 = [ 0, True, 'v'] # numpy will automatically convert lists with multiple types, so be careful
print(np.array(myList1))

#    2. Have dimensions (or 'axes') of the same length

myList0 = [ 0, [1],[[1],2]] # works fine as a list, but causes weird behaviour when converted to a numpy array
print(np.array(myList0))


[1 2 3]
[4 5 6]
1
6
[0 1]
['0' 'True' 'v']
[0 list([1]) list([[1], 2])]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:26: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [16]:
# Numpy arrays have lots of useful "attributes"

animals = np.array([['cat', 'dog'],['snake', 'rhino'], ['monkey', 'spider']])
print(animals)

# .shape tells you the size of each dimension in the array
print(animals.shape)

# .dtype tells you the data type of the array
print(animals.dtype)


[['cat' 'dog']
 ['snake' 'rhino']
 ['monkey' 'spider']]
(3, 2)
<U6


In [ ]:
### EXCERCISE

animals = np.array([['cat', 'dog'],['snake', 'rhino'], ['monkey', 'spider']])

# Use for-loops, range, and .shape to print each element in the "animals" array


In [18]:






### SOLUTION
animals = np.array([['cat', 'dog'],['snake', 'rhino'], ['monkey', 'spider']])
for i in range(animals.shape[0]) :
    for j in range(animals.shape[1]) :
        print(animals[i][j])


AttributeError: 'int' object has no attribute 'shape'

In [44]:
# Slicing
# What if you only want to access a subset of an array?
# You can use "slicing" to access a part of an array
# Examples 1, 2, and 3b will work for lists too

ar = np.array([[0,2,4,6,8,10,12],[1,3,5,7,9,11,13],[1,1,3,5,8,13,21]])
print('ar:')
print(ar)
print('\nshape',ar.shape, '\n')

print('1.a)', ar[0][0:3]) #this will return the 0th, 1st, and 2nd elements of the 0th row
print('1.b)', ar[0][:3])

print('2.a)', ar[1][3:])
print('2.b)', ar[1][3:8])

print('3.a)', ar[2][[0,2,4,6]]) # can use integers to index individual elements
print('3.b)', ar[2][0:8:2])



ar
[[ 0  2  4  6  8 10 12]
 [ 1  3  5  7  9 11 13]
 [ 1  1  3  5  8 13 21]]

shape (3, 7) 

1.a) [0 2 4]
1.b) [0 2 4]
2.a) [ 7  9 11 13]
2.b) [ 7  9 11 13]
3.a) [ 1  3  8 21]
3.b) [ 1  3  8 21]


In [47]:
### Zeros & Ones
# You can create arrays of zeros and ones with np.zeros(<dimensions>) and np.arrays(<dimensions>)
# with a given set of dimensions
print('a')
two_by_two = np.ones([2,2])
print(two_by_two)

print('\nb')
zeros_3d = np.zeros([3,3,3])
print(zeros_3d)


a
[[1. 1.]
 [1. 1.]]

b
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [52]:
### Reshaping arrays
# It can be useful to reshape an array to different dimensions. 
# The .reshape(<new dimensions>) function lets you do this.
# for example an array with a single dimension of [27] can be 
# reshaped into an array of shape [3,3,3]
vector = np.arange(27) # np.arange() is a function that returns an array of floats (similar to range() but not quite the same)
print('\nvector\n', vector)
matrix = vector.reshape(3,9)
print('\nmatrix\n',matrix)
volume = matrix.reshape(3,3,3)
print('\nvolume\n',volume)


vector
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

matrix
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]

volume
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [20]:
### Why do arrays matter for brain imaging? 

import nibabel as nib
import matplotlib.pyplot as plt

brain_filename=''
brain_image = nib.load(brain_filename)
brain_volume = brain_image.get_fdata()

print(f'The brain image stored at {brain_filename} has dimensions: {brain_volume.shape}')


FileNotFoundError: No such file or no access: ''